<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>AutoTranslation</AssemblyName>
    <RootNamespace>AutoTranslation</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\..\1.6\Assemblies\</OutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <DebugType>portable</DebugType>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.*" PrivateAssets="all" />
    <PackageReference Include="Lib.Harmony.Ref" Version="2.3.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
